//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Övning_6._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Böker
    {
        public int BokNr { get; set; }
        public string Title { get; set; }
        public string Ämne { get; set; }
        public string PersonNr { get; set; }
        public Nullable<System.DateTime> Lånedatum { get; set; }
    
        public virtual Elev Elev { get; set; }
    }
}
